# Generated by Django 4.0.4 on 2022-05-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('banner', models.TextField()),
                ('content', models.TextField()),
                ('categories', models.CharField(max_length=30)),
            ],
        ),
    ]
