# Generated by Django 4.0.4 on 2022-05-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(max_length=120)),
                ('seo_description', models.CharField(max_length=120)),
                ('seo_keywords', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=120)),
                ('banner_src', models.CharField(max_length=120)),
                ('banner_alt', models.CharField(max_length=60)),
                ('banner_title', models.CharField(max_length=60)),
                ('updatedAt', models.CharField(max_length=30)),
                ('categories', models.CharField(max_length=30)),
                ('content', models.TextField()),
            ],
        ),
    ]
