# Generated by Django 4.0.4 on 2022-05-13 04:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_keywords',
            field=models.TextField(),
        ),
    ]
