# Generated by Django 4.0.4 on 2022-05-17 22:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_alter_post_content_alter_post_seo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner_src',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
