# Generated by Django 4.0.4 on 2022-05-22 01:06

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_post_banner_src'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('path', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('alt', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='banner_alt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='banner_src',
        ),
        migrations.RemoveField(
            model_name='post',
            name='banner_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(to='cms.image'),
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='cms.category'),
        ),
    ]
