# Generated by Django 4.0.4 on 2022-05-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_category_image_remove_post_banner_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='updatedAt',
            field=models.DateField(),
        ),
    ]
